# Generated by Django 2.2.2 on 2019-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
