# Generated by Django 2.2.3 on 2019-07-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentos', '0002_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido_p', models.CharField(max_length=40)),
                ('Apellido_m', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Alcaldia', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=120)),
                ('CPostal', models.IntegerField(max_length=7)),
                ('Genero', models.CharField(max_length=1)),
                ('Fecha_subscripcion', models.DateField(auto_now_add=True)),
                ('Telefono', models.CharField(max_length=14)),
                ('Nombre_p', models.CharField(max_length=20, null=True)),
                ('Genero_p', models.CharField(max_length=4, null=True)),
                ('Ciudad_p', models.CharField(max_length=20, null=True)),
                ('Pais_p', models.CharField(max_length=15, null=True)),
                ('Ojos_p', models.CharField(max_length=10, null=True)),
                ('Color_pelo_p', models.CharField(max_length=10, null=True)),
                ('Tipo_pelo_p', models.CharField(max_length=10, null=True)),
                ('Piel_p', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_compra', models.DateField(blank=True, null=True)),
                ('Num_cuentos', models.IntegerField(max_length=6)),
                ('Venta_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IP', models.CharField(max_length=1)),
                ('Id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Contenido', models.TextField(max_length=200000)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ventas', models.ManyToManyField(to='cuentos.Ventas')),
            ],
        ),
    ]
