# Generated by Django 2.2.3 on 2019-07-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentos', '0003_cliente_cuento_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido_p', models.CharField(max_length=40)),
                ('Apellido_m', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.BigIntegerField(max_length=14)),
                ('mensaje', models.TextField(max_length=2000)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuento',
            name='ventas',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Gafas_p',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cuento',
            field=models.ManyToManyField(to='cuentos.Cuento'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='IP',
            field=models.BooleanField(null=True),
        ),
    ]
